name: rotalog
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_screenutil: ^5.9.3
  flutter_tts: ^4.2.5
  get: ^4.7.3
  get_storage: ^2.1.1
  google_fonts: ^8.0.2
  google_nav_bar: ^5.0.7
  intl: ^0.20.2
  remixicon: ^4.9.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/icons/
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#121212"
  android: true
  ios: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf