// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCQJzx10DBqnK70SQ09Ex-WzYxSMkgds',
    appId: '1:158459868848:web:244c6fee55d344440e6d75',
    messagingSenderId: '158459868848',
    projectId: 'rotalog-99ee2',
    authDomain: 'rotalog-99ee2.firebaseapp.com',
    storageBucket: 'rotalog-99ee2.firebasestorage.app',
    measurementId: 'G-3CQ4RCN7BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0JHpMpfBcmiOlkYjM9g0R6t0kp12vAQ',
    appId: '1:158459868848:android:ac396f7d418ba0a30e6d75',
    messagingSenderId: '158459868848',
    projectId: 'rotalog-99ee2',
    storageBucket: 'rotalog-99ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihRCPEMquS1ivi_KMOyM0QwreNQTYGIA',
    appId: '1:158459868848:ios:1228cad6db92409d0e6d75',
    messagingSenderId: '158459868848',
    projectId: 'rotalog-99ee2',
    storageBucket: 'rotalog-99ee2.firebasestorage.app',
    iosBundleId: 'br.com.rotalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihRCPEMquS1ivi_KMOyM0QwreNQTYGIA',
    appId: '1:158459868848:ios:1228cad6db92409d0e6d75',
    messagingSenderId: '158459868848',
    projectId: 'rotalog-99ee2',
    storageBucket: 'rotalog-99ee2.firebasestorage.app',
    iosBundleId: 'br.com.rotalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtCQJzx10DBqnK70SQ09Ex-WzYxSMkgds',
    appId: '1:158459868848:web:12af7c774da154b00e6d75',
    messagingSenderId: '158459868848',
    projectId: 'rotalog-99ee2',
    authDomain: 'rotalog-99ee2.firebaseapp.com',
    storageBucket: 'rotalog-99ee2.firebasestorage.app',
    measurementId: 'G-604VTGJ7T8',
  );
}
